### ISSUE TITLE
Error while running the example program

### ISSUE THREAD

**Issue by shehand** [ballerina-guides/sonarqube-github-integration#25]
**Description:**
When run the example program described in the README.md file it gives an error called (wso2/github)GithubError {"message":"Organization should have a name"}

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    
OS - Ubuntu 18.04

**Steps to reproduce:**

**Related Issues:**

**Comment by anupama-pathirage** [comment]
Closing as we no longer maintain this repo.
